plugins
{
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'com.gluonhq.gluonfx-gradle-plugin' version '1.0.27'
}

group = 'com.example'
version = '1.0-SNAPSHOT'

java
{
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories
{
    mavenCentral()
}

javafx
{
    version = '21'
    modules = ['javafx.controls']
}

dependencies
{
    implementation 'com.google.code.gson:gson:2.10.1'
}

application
{
    mainClass = 'agendoc.AgendocApp'
    mainModule = 'agendoc'
}

gluonfx {
    target = 'host'

    reflectionList = [
        'agendoc.AgendocMain',
    ]
}